version: "3.8"
services:
  emit-logs:
    build:
      context: ./src/EmitLog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENV_HOST=rabbit
    depends_on:
      - receive-logs
    stdin_open: true      
    restart: on-failure
    container_name: pd2-rmq-emit-logs
  receive-logs:
    build:
      context: ./src/ReceiveLogs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ENV_HOST=rabbit
    depends_on:
      - rabbit
    stdin_open: true
    restart: on-failure    
    container_name: pd2-rmq-receive-logs
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
    restart: on-failure
    container_name: pd2-rabbitmq
